backend:
  name: github
  repo: mkazmiorders/KazmiCellars
  branch: main
  base_url: https://kazmicellars.com

media_folder: images/uploads
public_folder: /images/uploads

collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Home Page"
        name: "home"
        file: "index.html"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
